language: node_js
node_js:
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: dF7kDVNJzpyQjAJTUPZJ+scLzVjfBApeBXqMxAvns/Ip/fyN96comiTsSKRbdnaCgWPdIYfJxkP1APjjsfA0AaCzyvYb/kXrUHzPrbrK8l0lxsv3fKCoR7NSk1jVJ0Vo68wmBUQKf9KChW8Z/Z0J+GA4py9T7t6CZpiny7lk7p0=
  app: vesta-api
  on:
    repo: fsegouin/vesta-api
